version: '3'
services:
    app:
        build:
            context: .
            args:
                - NODE_ENV=development
        command: ./node_modules/.bin/nodemon --inspect=0.0.0.0:9229 server.js
        depends_on:
            - mysql
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 3000:3000
            - 9229:9229
        env_file:
            - .env
        environment:
            - NODE_ENV=development
    mysql:
        image: mysql:5.7
        restart: always
        volumes:
            - ./.db:/var/lib/mysql
        ports:
            - 6603:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dev
        logging:
            driver: none
    nginx:
        image: nginx:alpine
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./static:/opt/html
        ports:
            - 80:80
        links:
            - app:app
        logging:
            driver: none
    valhalla:
        image: gisops/valhalla:latest
        ports:
        - "8002:8002"
        volumes:
        - ./custom_files/:/custom_files
        environment:
        # The tile_file must be located in the `custom_files` folder.
        # The tile_file has priority and is used when valid.
        # If the tile_file doesn't exist, the url is used instead.
        # Don't blank out tile_url when you use tile_file and vice versa.
        - tile_urls=https://download.geofabrik.de/europe/andorra-latest.osm.pbf
        # Get correct bounding box from e.g. https://boundingbox.klokantech.com/
        - min_x=18 # -> Albania | -180 -> World
        - min_y=38 # -> Albania | -90  -> World
        - max_x=22 # -> Albania |  180 -> World
        - max_y=43 # -> Albania |  90  -> World
        - use_tiles_ignore_pbf=True
        - force_rebuild=False
        - force_rebuild_elevation=False
        - build_elevation=True
        - build_admins=True
        - build_time_zones=True